#!/command/with-contenv sh

# ==========================================================================
# EmbyServer 服务结束钩子（复刻 amilys /etc/services.d/emby-server/finish）
# 退出码为 3 表示 Emby 请求重启（不触发 s6 扫描停止），否则正常关停
# ==========================================================================
[ "${1}" -ne 3 ] && /command/s6-svscanctl -t /run/service

exit 0